#!/bin/sh

set -e

mkdir -p build/version

printf "// This is an autogenerated file. Any modifications will be overwritten during the build process\n" > build/version/version.h

git_version="$(git describe --abbrev=7 --dirty --always --tags)"

printf "#pragma once\n\n#define GIT_VERSION \"" >> build/version/version.h

printf "%s" "$git_version" >> build/version/version.h

printf "\"\n#define GIT_IS_DIRTY " >> build/version/version.h

if [[ "$git_version" == *"-dirty"* ]]; then
    printf "true" >> build/version/version.h
else
    printf "false" >> build/version/version.h
fi

printf "\n" >> build/version/version.h
